function(install_target)
    set(OPTIONVALUES )
    set(ONEVALUES "NAME")
    set(MULTIVALUES "FILES")
    cmake_parse_arguments(INSTALL_TARGET "${OPTIONVALUES}" "${ONEVALUES}" "${MULTIVALUES}" ${ARGN})
    if(COLA_INSTALL)
        install(TARGETS ${INSTALL_TARGET_NAME})
        #install(FILES INSTALL_TARGET_FILES )
    endif(COLA_INSTALL)
endfunction()